practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Attempt_Score__c.object
<CustomObject>
    <fields>
        <fullName>Exam_Attempt__c</fullName>
        <label>Exam Attempt</label>
        <referenceTo>Exam_Attempt__c</referenceTo>
        <relationshipLabel>Attempt Scores</relationshipLabel>
        <relationshipName>Attempt_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Exam_Category__c</fullName>
        <label>Exam Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Exam_Categories</valueSetName>
        </valueSet>
    </fields>
    <label>Attempt Score</label>
    <nameField>
        <displayFormat>Score-{00000}</displayFormat>
        <label>Attempt Score Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attempt Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Exam_Attempt__c.object
<CustomObject>
    <fields>
        <fullName>Exam_Type__c</fullName>
        <defaultValue>$CustomMetadata.Exam_Type__mdt.ADM_201.Label</defaultValue>
        <label>Exam Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Exam_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Exam Attempt</label>
    <nameField>
        <displayFormat>Attempt-{0000}</displayFormat>
        <label>Exam Attempt ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/objects/Exam_Category__mdt.object
<CustomObject>
    <description>Represents a category of questions on the related exam type. The category names and weights are based on the certification exam guides provided by Salesforce. The weight represents the portion of questions in the exam that fall into this category.</description>
    <fields>
        <fullName>Exam_Type__c</fullName>
        <label>Exam Type</label>
        <referenceTo>Exam_Type__mdt</referenceTo>
        <relationshipLabel>Exam Categories</relationshipLabel>
        <relationshipName>Exam_Categories</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Exam Category</label>
    <pluralLabel>Exam Categories</pluralLabel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Exam_Type__mdt.object
<CustomObject>
    <label>Exam Type</label>
    <pluralLabel>Exam Types</pluralLabel>
</CustomObject>

practice-exam-tracker-sfdx/force-app/main/default/globalValueSets/Exam_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Organizational Setup</fullName>
    </customValue>
    <customValue>
        <fullName>User Setup</fullName>
    </customValue>
    <customValue>
        <fullName>Security and Access</fullName>
    </customValue>
    <customValue>
        <fullName>Standard and Custom Objects</fullName>
    </customValue>
    <customValue>
        <fullName>Sales and Marketing Applications</fullName>
    </customValue>
    <customValue>
        <fullName>Service and Support Applications</fullName>
    </customValue>
    <customValue>
        <fullName>Activity Management and Collaboration</fullName>
    </customValue>
    <customValue>
        <fullName>Data Management</fullName>
    </customValue>
    <customValue>
        <fullName>Analytics-Reports and Dashboards</fullName>
    </customValue>
    <customValue>
        <fullName>Workflow / Process Automation</fullName>
    </customValue>
    <customValue>
        <fullName>Desktop and Mobile Administration</fullName>
    </customValue>
    <customValue>
        <fullName>AppExchange</fullName>
    </customValue>
    <customValue>
        <fullName>Data Modeling and Management</fullName>
    </customValue>
    <customValue>
        <fullName>Debug and Deployment Tools</fullName>
    </customValue>
    <customValue>
        <fullName>Logic and Process Automation</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce Fundamentals</fullName>
    </customValue>
    <customValue>
        <fullName>Testing</fullName>
    </customValue>
    <customValue>
        <fullName>User Interface</fullName>
    </customValue>
    <masterLabel>Exam Categories</masterLabel>
</GlobalValueSet>

practice-exam-tracker-sfdx/force-app/main/default/globalValueSets/Exam_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ADM 201</fullName>
    </customValue>
    <customValue>
        <fullName>PD1</fullName>
    </customValue>
    <masterLabel>Exam Types</masterLabel>
</GlobalValueSet>

practice-exam-tracker-sfdx/pet-app/main/default/classes/Constants.cls
public class Constants {
    
    public static final List<Schema.PicklistEntry> EXAM_TYPE_PICKLIST_VALUES {
        get {
            if(EXAM_TYPE_PICKLIST_VALUES == null){
                EXAM_TYPE_PICKLIST_VALUES = Schema.SObjectType.Exam_Attempt__c.fields.Exam_Type__c.getPicklistValues();
            }
            return EXAM_TYPE_PICKLIST_VALUES;
        }
        set;
    } 
    
    public static final Map<String, Schema.PicklistEntry> EXAM_TYPE_PICKLIST_MAP{
        get {
            if(EXAM_TYPE_PICKLIST_MAP == null){
                EXAM_TYPE_PICKLIST_MAP = new Map<String, Schema.PicklistEntry>();
                for(Schema.PicklistEntry pe : EXAM_TYPE_PICKLIST_VALUES){
                    EXAM_TYPE_PICKLIST_MAP.put(pe.getLabel(), pe);
                }
            }
            
            return EXAM_TYPE_PICKLIST_MAP;
        }
        set;
    }
    
    public static final List<Schema.PicklistEntry> EXAM_CATEGORY_PICKLIST_VALUES {
        get {
            if(EXAM_CATEGORY_PICKLIST_VALUES == null){
                EXAM_CATEGORY_PICKLIST_VALUES = Schema.SObjectType.Attempt_Score__c.fields.Exam_Category__c.getPicklistValues();
            }
            return EXAM_CATEGORY_PICKLIST_VALUES;
        }
        set;
    }
    
    public static final Map<String, Schema.PicklistEntry> EXAM_CATEGORY_PICKLIST_MAP{
        get {
            EXAM_CATEGORY_PICKLIST_MAP = new Map<String, Schema.PicklistEntry>();
            for(Schema.PicklistEntry pe : EXAM_CATEGORY_PICKLIST_VALUES){
                EXAM_CATEGORY_PICKLIST_MAP.put(pe.getLabel(), pe);
            }
            return EXAM_CATEGORY_PICKLIST_MAP;
        }
        set;
    }
    
    public static final List<Exam_Category__mdt> EXAM_CATEGORY_METADATA_RECORDS {
        get {
            if(EXAM_CATEGORY_METADATA_RECORDS == null){
                EXAM_CATEGORY_METADATA_RECORDS = [SELECT MasterLabel, Exam_Type__c, Weight__c
                                                  FROM Exam_Category__mdt];
            }
            return EXAM_CATEGORY_METADATA_RECORDS;
        }
        set;
    } 
    
    public static final Map<String, List<String>> EXAM_TYPE_TO_CATEGORY_MAP {
        get{
            EXAM_TYPE_TO_CATEGORY_MAP = new Map<String, List<String>>();
            List<Exam_Type__mdt> examTypeRecords = [SELECT MasterLabel, Id FROM Exam_Type__mdt];
            Map<Id, Exam_Type__mdt> examTypeMap = new Map<Id, Exam_Type__mdt>(examTypeRecords);
            for(Exam_Category__mdt ec : EXAM_CATEGORY_METADATA_RECORDS){
                if(EXAM_TYPE_TO_CATEGORY_MAP.containsKey(examTypeMap.get(ec.Exam_Type__c).MasterLabel)){
                    List<String> catList = EXAM_TYPE_TO_CATEGORY_MAP.get(examTypeMap.get(ec.Exam_Type__c).MasterLabel);
                    catList.add(ec.MasterLabel);
                    EXAM_TYPE_TO_CATEGORY_MAP.put(examTypeMap.get(ec.Exam_Type__c).MasterLabel, catList);
                } else {
                    List<String> catList = new List<String>();
                    catList.add(ec.MasterLabel);
                    EXAM_TYPE_TO_CATEGORY_MAP.put(examTypeMap.get(ec.Exam_Type__c).MasterLabel, catList);
                }
            }
            return EXAM_TYPE_TO_CATEGORY_MAP;
        }
        set;
    }
    
    public static final Map<String, List<String>> EXAM_TYPE_TO_SORTED_CATEGORY_MAP {
        get{
            if(EXAM_TYPE_TO_SORTED_CATEGORY_MAP == null){
                EXAM_TYPE_TO_SORTED_CATEGORY_MAP = new Map<String, List<String>>();
                Map<Id, Exam_Type__mdt> examTypeMap = new Map<Id, Exam_Type__mdt>([SELECT MasterLabel, Id FROM Exam_Type__mdt]);
                for(Exam_Category__mdt ec : SORTED_EXAM_CATEGORY_MD_RECORDS){
                    if(EXAM_TYPE_TO_SORTED_CATEGORY_MAP.containsKey(examTypeMap.get(ec.Exam_Type__c).MasterLabel)){
                        List<String> catList = EXAM_TYPE_TO_SORTED_CATEGORY_MAP.get(examTypeMap.get(ec.Exam_Type__c).MasterLabel);
                        catList.add(ec.MasterLabel);
                        EXAM_TYPE_TO_SORTED_CATEGORY_MAP.put(examTypeMap.get(ec.Exam_Type__c).MasterLabel, catList);
                    } else {
                        List<String> catList = new List<String>();
                        catList.add(ec.MasterLabel);
                        EXAM_TYPE_TO_SORTED_CATEGORY_MAP.put(examTypeMap.get(ec.Exam_Type__c).MasterLabel, catList);
                    }
                }
            }
            
            return EXAM_TYPE_TO_SORTED_CATEGORY_MAP;
        }
        set;
    }
    
    public static final List<Exam_Category__mdt> SORTED_EXAM_CATEGORY_MD_RECORDS {
        get {
            if(SORTED_EXAM_CATEGORY_MD_RECORDS == null){
                SORTED_EXAM_CATEGORY_MD_RECORDS = new List<Exam_Category__mdt>();
                for(Schema.PicklistEntry pe : EXAM_CATEGORY_PICKLIST_VALUES){
                    for(Exam_Category__mdt ec : EXAM_CATEGORY_METADATA_RECORDS){
                        if(ec.MasterLabel == pe.getLabel()){
                            SORTED_EXAM_CATEGORY_MD_RECORDS.add(ec);
                        }
                    }
                }
            }
            return SORTED_EXAM_CATEGORY_MD_RECORDS;
        }
        set;
    }
    
    public static final Map<String, Decimal> EXAM_CATEGORY_WEIGHTS {
        get{
            if(EXAM_CATEGORY_WEIGHTS == null){
                EXAM_CATEGORY_WEIGHTS = new Map<String, Decimal>();
                for(Exam_Category__mdt ecmdt : EXAM_CATEGORY_METADATA_RECORDS){
                    for(String s : EXAM_CATEGORY_PICKLIST_MAP.keySet()){
                        if(ecmdt.MasterLabel == s){
                            EXAM_CATEGORY_WEIGHTS.put(s, ecmdt.Weight__c);
                        }
                    }
                }
            }
            return EXAM_CATEGORY_WEIGHTS;
        }
        set;
    }
    
    public static final Map<String, Schema.RecordTypeInfo> EXAM_ATTEMPT_RECORD_TYPES {
        get {
            if(EXAM_ATTEMPT_RECORD_TYPES == null){
                EXAM_ATTEMPT_RECORD_TYPES = Schema.SObjectType.Exam_Attempt__c.getRecordTypeInfosByDeveloperName();
            }
            return EXAM_ATTEMPT_RECORD_TYPES;
        }
        set;
    } 
    
}