practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Attempt_Score__c.object
<CustomObject>
    <fields>
        <fullName>Exam_Category__c</fullName>
        <label>Exam Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Exam_Categories</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Percent__c</fullName>
        <label>Percent</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weighted_Percent__c</fullName>
        <label>Weighted Percent</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <label>Attempt Score</label>
    <nameField>
        <displayFormat>Score-{00000}</displayFormat>
        <label>Attempt Score Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attempt Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/force-app/main/default/globalValueSets/Exam_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Organizational Setup</fullName>
    </customValue>
    <customValue>
        <fullName>User Setup</fullName>
    </customValue>
    <customValue>
        <fullName>Security and Access</fullName>
    </customValue>
    <customValue>
        <fullName>Standard and Custom Objects</fullName>
    </customValue>
    <customValue>
        <fullName>Sales and Marketing Applications</fullName>
    </customValue>
    <customValue>
        <fullName>Service and Support Applications</fullName>
    </customValue>
    <customValue>
        <fullName>Activity Management and Collaboration</fullName>
    </customValue>
    <customValue>
        <fullName>Data Management</fullName>
    </customValue>
    <customValue>
        <fullName>Analytics-Reports and Dashboards</fullName>
    </customValue>
    <customValue>
        <fullName>Workflow / Process Automation</fullName>
    </customValue>
    <customValue>
        <fullName>Desktop and Mobile Administration</fullName>
    </customValue>
    <customValue>
        <fullName>AppExchange</fullName>
    </customValue>
    <customValue>
        <fullName>Data Modeling and Management</fullName>
    </customValue>
    <customValue>
        <fullName>Debug and Deployment Tools</fullName>
    </customValue>
    <customValue>
        <fullName>Logic and Process Automation</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce Fundamentals</fullName>
    </customValue>
    <customValue>
        <fullName>Testing</fullName>
    </customValue>
    <customValue>
        <fullName>User Interface</fullName>
    </customValue>
    <masterLabel>Exam Categories</masterLabel>
</GlobalValueSet>

practice-exam-tracker-sfdx/force-app/main/default/classes/AttemptScoreValidationAndUpdateHelper.cls
public class AttemptScoreValidationAndUpdateHelper {

    public static void updateAttemptScoreWeightedPercent(List<Attempt_Score__c> scores){
        System.debug('--AttemptScoreValidationAndUpdateHelper.updateAttemptScoreWeightedPercent--');
        System.debug('Input list of scores: ' + scores);
        
        for(Attempt_Score__c a : scores){
            System.debug('Exam_Category__c: ' + ((a.Exam_Category__c== null)?'is Null': a.Exam_Category__c));
            if(a.Percent__c == null){
                a.Percent__c = 0;
            }
            System.debug('Associate Weight: ' + Constants.EXAM_CATEGORY_WEIGHTS.get(a.Exam_Category__c));
            System.debug('Percent * Weight: ' + a.Percent__c * Constants.EXAM_CATEGORY_WEIGHTS.get(a.Exam_Category__c));
            a.Weighted_Percent__c = (a.Percent__c * Constants.EXAM_CATEGORY_WEIGHTS.get(a.Exam_Category__c))/100;
        }
        System.debug('-------------------------');
    }
    
}