practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Attempt_Score__c.object
<CustomObject>
    <fields>
        <fullName>Exam_Attempt__c</fullName>
        <label>Exam Attempt</label>
        <referenceTo>Exam_Attempt__c</referenceTo>
        <relationshipLabel>Attempt Scores</relationshipLabel>
        <relationshipName>Attempt_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Exam_Category__c</fullName>
        <label>Exam Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Exam_Categories</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Percent__c</fullName>
        <label>Percent</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Attempt Score</label>
    <nameField>
        <displayFormat>Score-{00000}</displayFormat>
        <label>Attempt Score Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attempt Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Exam_Attempt__c.object
<CustomObject>
    <fields>
        <fullName>Associate__c</fullName>
        <label>Associate</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Exam Attempts</relationshipLabel>
        <relationshipName>Exam_Attempts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Attempt_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Attempt Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Attempt_Number__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Attempt Number</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Exam_Type__c</fullName>
        <defaultValue>$CustomMetadata.Exam_Type__mdt.ADM_201.Label</defaultValue>
        <label>Exam Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Exam_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Practice_Exam_Version__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Practice Exam Version</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Exam Attempt</label>
    <nameField>
        <displayFormat>Attempt-{0000}</displayFormat>
        <label>Exam Attempt ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Attempts</pluralLabel>
    <recordTypes>
        <fullName>Certification</fullName>
        <active>true</active>
        <label>Certification</label>
    </recordTypes>
    <recordTypes>
        <fullName>Practice</fullName>
        <active>true</active>
        <label>Practice</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/objects/Exam_Category__mdt.object
<CustomObject>
    <description>Represents a category of questions on the related exam type. The category names and weights are based on the certification exam guides provided by Salesforce. The weight represents the portion of questions in the exam that fall into this category.</description>
    <fields>
        <fullName>Exam_Type__c</fullName>
        <label>Exam Type</label>
        <referenceTo>Exam_Type__mdt</referenceTo>
        <relationshipLabel>Exam Categories</relationshipLabel>
        <relationshipName>Exam_Categories</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Exam Category</label>
    <pluralLabel>Exam Categories</pluralLabel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Exam_Type__mdt.object
<CustomObject>
    <label>Exam Type</label>
    <pluralLabel>Exam Types</pluralLabel>
</CustomObject>

practice-exam-tracker-sfdx/force-app/main/default/globalValueSets/Exam_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Organizational Setup</fullName>
    </customValue>
    <customValue>
        <fullName>User Setup</fullName>
    </customValue>
    <customValue>
        <fullName>Security and Access</fullName>
    </customValue>
    <customValue>
        <fullName>Standard and Custom Objects</fullName>
    </customValue>
    <customValue>
        <fullName>Sales and Marketing Applications</fullName>
    </customValue>
    <customValue>
        <fullName>Service and Support Applications</fullName>
    </customValue>
    <customValue>
        <fullName>Activity Management and Collaboration</fullName>
    </customValue>
    <customValue>
        <fullName>Data Management</fullName>
    </customValue>
    <customValue>
        <fullName>Analytics-Reports and Dashboards</fullName>
    </customValue>
    <customValue>
        <fullName>Workflow / Process Automation</fullName>
    </customValue>
    <customValue>
        <fullName>Desktop and Mobile Administration</fullName>
    </customValue>
    <customValue>
        <fullName>AppExchange</fullName>
    </customValue>
    <customValue>
        <fullName>Data Modeling and Management</fullName>
    </customValue>
    <customValue>
        <fullName>Debug and Deployment Tools</fullName>
    </customValue>
    <customValue>
        <fullName>Logic and Process Automation</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce Fundamentals</fullName>
    </customValue>
    <customValue>
        <fullName>Testing</fullName>
    </customValue>
    <customValue>
        <fullName>User Interface</fullName>
    </customValue>
    <masterLabel>Exam Categories</masterLabel>
</GlobalValueSet>

practice-exam-tracker-sfdx/force-app/main/default/globalValueSets/Exam_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ADM 201</fullName>
    </customValue>
    <customValue>
        <fullName>PD1</fullName>
    </customValue>
    <masterLabel>Exam Types</masterLabel>
</GlobalValueSet>

practice-exam-tracker-sfdx/pet-app/main/default/classes/PETTestDataFactory.cls
@isTest
public class PETTestDataFactory {
    public static List<Exam_Attempt__c> createExamAttempts(List<Contact> associates, Boolean practice){
        List<Exam_Attempt__c> attemptList = new List<Exam_Attempt__c>();
        for(Contact c : associates){
            Exam_Attempt__c attempt = new Exam_Attempt__c();
            attempt.Associate__c = c.Id;
            attempt.Attempt_Date__c = Date.Today();
            attempt.Attempt_Number__c = 1;
            attempt.Exam_Type__c = Constants.EXAM_TYPE_PICKLIST_VALUES[0].getValue();
            attempt.RecordTypeId = Constants.EXAM_ATTEMPT_RECORD_TYPES.get(practice?'Practice':'Certification').getRecordTypeId();
            attempt.Practice_Exam_Version__c = practice?1:null;
            attemptList.add(attempt);
        }
        return attemptList;
    }
    
    public static List<Exam_Attempt__c> createExamAttempts(List<Contact> associates, Boolean practice, Date dateOfAttempt){
        List<Exam_Attempt__c> attemptList = new List<Exam_Attempt__c>();
        for(Contact c : associates){
            Exam_Attempt__c attempt = new Exam_Attempt__c();
            attempt.Associate__c = c.Id;
            attempt.Attempt_Date__c = dateOfAttempt;
            attempt.Attempt_Number__c = 1;
            attempt.Exam_Type__c = Constants.EXAM_TYPE_PICKLIST_VALUES[0].getValue();
            attempt.RecordTypeId = Constants.EXAM_ATTEMPT_RECORD_TYPES.get(practice?'Practice':'Certification').getRecordTypeId();
            attempt.Practice_Exam_Version__c = practice?1:null;
            attemptList.add(attempt);
        }
        return attemptList;
    }
    
    public static List<Attempt_Score__c> createExamAttemptScores(List<Exam_Attempt__c> attempts){
        List<Attempt_Score__c> scoresList = new List<Attempt_Score__c>();
        for(Exam_Attempt__c ea : attempts){
            for(Exam_Category__mdt ecmdt : [SELECT MasterLabel, Exam_Type__c, Weight__c FROM Exam_Category__mdt WHERE Exam_Type__r.MasterLabel = :ea.Exam_Type__c]){
                scoresList.add(new Attempt_Score__c(Exam_Attempt__c = ea.Id, Exam_Category__c = ecmdt.MasterLabel, Percent__c = 100));
            }
        }
        return scoresList;
    }
    
    public static List<Attempt_Score__c> createExamAttemptScores(List<Exam_Attempt__c> attempts, Boolean passing){
        List<Attempt_Score__c> scoresList = new List<Attempt_Score__c>();
        for(Exam_Attempt__c ea : attempts){
            for(Exam_Category__mdt ecmdt : [SELECT MasterLabel, Exam_Type__c, Weight__c FROM Exam_Category__mdt WHERE Exam_Type__r.MasterLabel = :ea.Exam_Type__c]){
                if(passing){
                    scoresList.add(new Attempt_Score__c(Exam_Attempt__c = ea.Id, Exam_Category__c = ecmdt.MasterLabel, Percent__c = 100));
                } else {
                    scoresList.add(new Attempt_Score__c(Exam_Attempt__c = ea.Id, Exam_Category__c = ecmdt.MasterLabel, Percent__c = 1));
                }
            
            }
        }
        return scoresList;
    }
}