practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Attempt_Score__c.object
<CustomObject>
    <fields>
        <fullName>Exam_Attempt__c</fullName>
        <label>Exam Attempt</label>
        <referenceTo>Exam_Attempt__c</referenceTo>
        <relationshipLabel>Attempt Scores</relationshipLabel>
        <relationshipName>Attempt_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Exam_Category__c</fullName>
        <label>Exam Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Exam_Categories</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Percent__c</fullName>
        <label>Percent</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weighted_Percent__c</fullName>
        <label>Weighted Percent</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <label>Attempt Score</label>
    <nameField>
        <displayFormat>Score-{00000}</displayFormat>
        <label>Attempt Score Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attempt Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Exam_Attempt__c.object
<CustomObject>
    <fields>
        <fullName>Exam_Type__c</fullName>
        <defaultValue>$CustomMetadata.Exam_Type__mdt.ADM_201.Label</defaultValue>
        <label>Exam Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Exam_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Exam Attempt</label>
    <nameField>
        <displayFormat>Attempt-{0000}</displayFormat>
        <label>Exam Attempt ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/force-app/main/default/globalValueSets/Exam_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Organizational Setup</fullName>
    </customValue>
    <customValue>
        <fullName>User Setup</fullName>
    </customValue>
    <customValue>
        <fullName>Security and Access</fullName>
    </customValue>
    <customValue>
        <fullName>Standard and Custom Objects</fullName>
    </customValue>
    <customValue>
        <fullName>Sales and Marketing Applications</fullName>
    </customValue>
    <customValue>
        <fullName>Service and Support Applications</fullName>
    </customValue>
    <customValue>
        <fullName>Activity Management and Collaboration</fullName>
    </customValue>
    <customValue>
        <fullName>Data Management</fullName>
    </customValue>
    <customValue>
        <fullName>Analytics-Reports and Dashboards</fullName>
    </customValue>
    <customValue>
        <fullName>Workflow / Process Automation</fullName>
    </customValue>
    <customValue>
        <fullName>Desktop and Mobile Administration</fullName>
    </customValue>
    <customValue>
        <fullName>AppExchange</fullName>
    </customValue>
    <customValue>
        <fullName>Data Modeling and Management</fullName>
    </customValue>
    <customValue>
        <fullName>Debug and Deployment Tools</fullName>
    </customValue>
    <customValue>
        <fullName>Logic and Process Automation</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce Fundamentals</fullName>
    </customValue>
    <customValue>
        <fullName>Testing</fullName>
    </customValue>
    <customValue>
        <fullName>User Interface</fullName>
    </customValue>
    <masterLabel>Exam Categories</masterLabel>
</GlobalValueSet>

practice-exam-tracker-sfdx/force-app/main/default/globalValueSets/Exam_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ADM 201</fullName>
    </customValue>
    <customValue>
        <fullName>PD1</fullName>
    </customValue>
    <masterLabel>Exam Types</masterLabel>
</GlobalValueSet>

practice-exam-tracker-sfdx/PackageFormat/classes/AttemptScoreValidationAndUpdateHelper.cls
public class AttemptScoreValidationAndUpdateHelper {
    
    public static void updateAttemptScoreWeightedPercent(List<Attempt_Score__c> scores){
        for(Attempt_Score__c a : scores){
            if(a.Percent__c == null){
                a.Percent__c = 0;
            }
            a.Weighted_Percent__c = (a.Percent__c * Constants.EXAM_CATEGORY_WEIGHTS.get(a.Exam_Category__c))/100;
        }
    }
    
    public static void validateCategoryMatchesExamAttemptType(List<Attempt_Score__c> scores){
        Map<Id, Exam_Attempt__c> relatedAttempts = getRelatedExamAttemptsMap(scores);
        for(Attempt_Score__c score : scores){
            String examType = relatedAttempts.get(score.Exam_Attempt__c).Exam_Type__c;
            List<String> catList = Constants.EXAM_TYPE_TO_CATEGORY_MAP.get(examType);
            if(!catList.contains(score.Exam_Category__c)){
                score.Exam_Category__c.addError('The category you chose does not exist for the associated exam type ('+ examType + ').');
            }
        }
        
    }
    
    public static Map<Id, Exam_Attempt__c> getRelatedExamAttemptsMap(List<Attempt_Score__c> scores){
        List<Id> attemptIds = new List<Id>();
        for(Attempt_Score__c score : scores){
            attemptIds.add(score.Exam_Attempt__c);
        }
        List<Exam_Attempt__c> relatedAttempts = [SELECT Id, Exam_Type__c 
                                                FROM Exam_Attempt__c
                                                WHERE Id IN :attemptIds];
        
        return new Map<Id, Exam_Attempt__c>(relatedAttempts);
    }
    
    public static void preventDuplicates(List<Attempt_Score__c> scores){
        List<AggregateResult> arList = [SELECT COUNT(Id), Exam_Attempt__c, Exam_Category__c FROM Attempt_Score__c
                                       GROUP BY Exam_Attempt__c, Exam_Category__c];
        for(AggregateResult ar : arList){
            for(Attempt_Score__c score : scores){
                if(((Id)ar.get('Exam_Attempt__c') == score.Exam_Attempt__c) && ((String)ar.get('Exam_Category__c') == score.Exam_Category__c)){
                    if((Integer)ar.get('expr0') != null && (Integer)ar.get('expr0') != 0){
                        score.addError('This attempt already has a score for this category.');
                    }
                }
            }
        }
    }
    
}