practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Attempt_Score__c.object
<CustomObject>
    <fields>
        <fullName>Exam_Attempt__c</fullName>
        <label>Exam Attempt</label>
        <referenceTo>Exam_Attempt__c</referenceTo>
        <relationshipLabel>Attempt Scores</relationshipLabel>
        <relationshipName>Attempt_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Exam_Category__c</fullName>
        <label>Exam Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Exam_Categories</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Percent__c</fullName>
        <label>Percent</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weighted_Percent__c</fullName>
        <label>Weighted Percent</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <label>Attempt Score</label>
    <nameField>
        <displayFormat>Score-{00000}</displayFormat>
        <label>Attempt Score Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attempt Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Batch__c.object
<CustomObject>
    <label>Batch</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Batch_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Associate__c</fullName>
        <label>Associate</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Batch Assignments</relationshipLabel>
        <relationshipName>Batch_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Batch__c</fullName>
        <label>Batch</label>
        <referenceTo>Batch__c</referenceTo>
        <relationshipLabel>Associates</relationshipLabel>
        <relationshipName>Batch_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Batch Assignment</label>
    <nameField>
        <displayFormat>{YY}{MM}-{0000}</displayFormat>
        <label>Batch Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Exam_Attempt__c.object
<CustomObject>
    <fields>
        <fullName>Associate__c</fullName>
        <label>Associate</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Exam Attempts</relationshipLabel>
        <relationshipName>Exam_Attempts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Attempt_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Attempt Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Attempt_Number__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Attempt Number</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Exam_Type__c</fullName>
        <defaultValue>$CustomMetadata.Exam_Type__mdt.ADM_201.Label</defaultValue>
        <label>Exam Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Exam_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Exam Attempt</label>
    <nameField>
        <displayFormat>Attempt-{0000}</displayFormat>
        <label>Exam Attempt ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/objects/Exam_Category__mdt.object
<CustomObject>
    <description>Represents a category of questions on the related exam type. The category names and weights are based on the certification exam guides provided by Salesforce. The weight represents the portion of questions in the exam that fall into this category.</description>
    <fields>
        <fullName>Exam_Type__c</fullName>
        <label>Exam Type</label>
        <referenceTo>Exam_Type__mdt</referenceTo>
        <relationshipLabel>Exam Categories</relationshipLabel>
        <relationshipName>Exam_Categories</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Exam Category</label>
    <pluralLabel>Exam Categories</pluralLabel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Exam_Type__mdt.object
<CustomObject>
    <label>Exam Type</label>
    <pluralLabel>Exam Types</pluralLabel>
</CustomObject>

practice-exam-tracker-sfdx/force-app/main/default/globalValueSets/Exam_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Organizational Setup</fullName>
    </customValue>
    <customValue>
        <fullName>User Setup</fullName>
    </customValue>
    <customValue>
        <fullName>Security and Access</fullName>
    </customValue>
    <customValue>
        <fullName>Standard and Custom Objects</fullName>
    </customValue>
    <customValue>
        <fullName>Sales and Marketing Applications</fullName>
    </customValue>
    <customValue>
        <fullName>Service and Support Applications</fullName>
    </customValue>
    <customValue>
        <fullName>Activity Management and Collaboration</fullName>
    </customValue>
    <customValue>
        <fullName>Data Management</fullName>
    </customValue>
    <customValue>
        <fullName>Analytics-Reports and Dashboards</fullName>
    </customValue>
    <customValue>
        <fullName>Workflow / Process Automation</fullName>
    </customValue>
    <customValue>
        <fullName>Desktop and Mobile Administration</fullName>
    </customValue>
    <customValue>
        <fullName>AppExchange</fullName>
    </customValue>
    <customValue>
        <fullName>Data Modeling and Management</fullName>
    </customValue>
    <customValue>
        <fullName>Debug and Deployment Tools</fullName>
    </customValue>
    <customValue>
        <fullName>Logic and Process Automation</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce Fundamentals</fullName>
    </customValue>
    <customValue>
        <fullName>Testing</fullName>
    </customValue>
    <customValue>
        <fullName>User Interface</fullName>
    </customValue>
    <masterLabel>Exam Categories</masterLabel>
</GlobalValueSet>

practice-exam-tracker-sfdx/force-app/main/default/globalValueSets/Exam_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ADM 201</fullName>
    </customValue>
    <customValue>
        <fullName>PD1</fullName>
    </customValue>
    <masterLabel>Exam Types</masterLabel>
</GlobalValueSet>

practice-exam-tracker-sfdx/PackageFormat/sfdx project/classes/AttemptScoreValidationAndUpdateTest.cls
@isTest
public class AttemptScoreValidationAndUpdateTest {

	@testSetup
    public static void makeData(){
        //create one associate
        List<Contact> associates = TestDataFactory.createNAssociates(1);
        insert associates;
        //create one batch
        List<Batch__c> batches = TestDataFactory.createNBatches(1, Date.newInstance(2019, 01, 01));
        insert batches;
        //create a batch assignment for that one associate and that one batch.
        List<Batch_Assignment__c> assignments = TestDataFactory.createBatchAssignments(associates, batches[0]);
        insert assignments;
        //create an exam attempt for that associate.
        List<Exam_Attempt__c> attempts = TestDataFactory.createExamAttempts(associates, true, Date.newInstance(2019, 01, 05));
        insert attempts;
    }   
    
    @isTest
    public static void updateAttemptScoreWeightedPercentSinglePosTest(){
        List<Exam_Attempt__c> attempts = [SELECT Id, Associate__c, Attempt_Date__c, Attempt_Number__c, Exam_Type__c FROM Exam_Attempt__c];
        List<Attempt_Score__c> scoresList = new List<Attempt_Score__c>();
        for(Exam_Attempt__c ea : attempts){
            for(Exam_Category__mdt ecmdt : [SELECT MasterLabel, Exam_Type__c, Weight__c FROM Exam_Category__mdt WHERE Exam_Type__r.MasterLabel = :ea.Exam_Type__c]){
                scoresList.add(new Attempt_Score__c(Exam_Attempt__c = ea.Id, Exam_Category__c = ecmdt.MasterLabel, Percent__c = 10));
            }
        }
        insert scoresList;
        scoresList = [SELECT Id, Exam_Attempt__c, Exam_Category__c, Percent__c, Weighted_Percent__c FROM Attempt_Score__c];
        for(Attempt_Score__c score : scoresList){
            Decimal weight = Constants.EXAM_CATEGORY_WEIGHTS.get(score.Exam_Category__c);
            Decimal weightedPercent = score.Weighted_Percent__c;
            System.assertEquals(weight*.1, weightedPercent);
        }
        
    }
    
    @isTest
    public static void validateCategoryMatchesExamAttemptTypeSinglePosTest(){
        List<Exam_Attempt__c> attempts = [SELECT Id, Associate__c, Attempt_Date__c, Attempt_Number__c, Exam_Type__c FROM Exam_Attempt__c];
        List<Attempt_Score__c> scoresList = new List<Attempt_Score__c>();
        for(Exam_Attempt__c ea : attempts){
            for(Exam_Category__mdt ecmdt : [SELECT MasterLabel, Exam_Type__c, Weight__c FROM Exam_Category__mdt WHERE Exam_Type__r.MasterLabel != :ea.Exam_Type__c]){
                scoresList.add(new Attempt_Score__c(Exam_Attempt__c = ea.Id, Exam_Category__c = ecmdt.MasterLabel, Percent__c = 100));
            }
        }
        try {
            insert scoresList;
        } catch (Exception e){
            System.debug(LoggingLevel.INFO, 'An exception was thrown while trying to insert attempt score records. This was expected.');
            System.assert(e.getMessage().contains('The category you chose does not exist for the associated exam type'));
        }
        
        System.assertEquals(0, [SELECT Count() FROM Attempt_Score__c]);
        
    }
}