practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Attempt_Score__c.object
<CustomObject>
    <fields>
        <fullName>Exam_Attempt__c</fullName>
        <label>Exam Attempt</label>
        <referenceTo>Exam_Attempt__c</referenceTo>
        <relationshipLabel>Attempt Scores</relationshipLabel>
        <relationshipName>Attempt_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attempt Score</label>
    <nameField>
        <displayFormat>Score-{00000}</displayFormat>
        <label>Attempt Score Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attempt Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Batch__c.object
<CustomObject>
    <label>Batch</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Batch_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Batch__c</fullName>
        <label>Batch</label>
        <referenceTo>Batch__c</referenceTo>
        <relationshipLabel>Associates</relationshipLabel>
        <relationshipName>Batch_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Batch Assignment</label>
    <nameField>
        <displayFormat>{YY}{MM}-{0000}</displayFormat>
        <label>Batch Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Exam_Attempt__c.object
<CustomObject>
    <fields>
        <fullName>Days_Since_Start_Of_Batch__c</fullName>
        <label>Days Since Start Of Batch</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Overall_Score__c</fullName>
        <label>Overall Score</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Pass__c</fullName>
        <formula>(TEXT(Exam_Type__c) =  $CustomMetadata.Exam_Type__mdt.ADM_201.MasterLabel 
     &amp;&amp;  Overall_Score__c  &gt;=   $CustomMetadata.Exam_Type__mdt.ADM_201.Passing_Score__c)
||
(TEXT(Exam_Type__c) =  $CustomMetadata.Exam_Type__mdt.PD1.MasterLabel 
     &amp;&amp;  Overall_Score__c  &gt;=   $CustomMetadata.Exam_Type__mdt.PD1.Passing_Score__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pass</label>
        <type>Checkbox</type>
    </fields>
    <label>Exam Attempt</label>
    <nameField>
        <displayFormat>Attempt-{0000}</displayFormat>
        <label>Exam Attempt ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/force-app/main/default/classes/ExamValidationAndUpdateTest.cls
@isTest
public class ExamValidationAndUpdateTest {

    @TestSetup
    static void makeData(){
        //create one associate
        List<Contact> associates = TestDataFactory.createNAssociates(1);
        insert associates;
        //create one batch
        List<Batch__c> batches = TestDataFactory.createNBatches(1, Date.newInstance(2019, 01, 01));
        insert batches;
        //create a batch assignment for that one associate and that one batch.
        List<Batch_Assignment__c> assignments = TestDataFactory.createBatchAssignments(associates, batches[0]);
        insert assignments;
    }

    @isTest
    public static void updateExamAttemptDaysSinceStartSinglePosTest(){
        List<Contact> associates = [SELECT Id FROM Contact];
        //Test
		List<Exam_Attempt__c> attempts = TestDataFactory.createExamAttempts(associates, true, Date.newInstance(2019, 01, 02));
        insert attempts;
        
        //Assertions
        for(Exam_Attempt__c ea : [SELECT Days_Since_Start_Of_Batch__c FROM Exam_Attempt__c]){
            System.assertEquals(1, ea.Days_Since_Start_Of_Batch__c);
        }
        
    }
    
    @isTest
    public static void updateExamAttemptOverallScoreSinglePosTest(){
        List<Contact> associates = [SELECT Id FROM Contact];
        //create exam attempt
        List<Exam_Attempt__c> attempts = TestDataFactory.createExamAttempts(associates, true, Date.newInstance(2019, 01, 03));
        insert attempts;

        List<Attempt_Score__c> scoresForAttempt = TestDataFactory.createExamAttemptScores(attempts);
        insert scoresForAttempt;
        System.debug([SELECT Count() FROM Attempt_Score__c]);
        

        Exam_Attempt__c attempt = [SELECT Id, Overall_Score__c, Pass__c FROM Exam_Attempt__c WHERE Id = :attempts[0].Id];
        System.assertEquals(100, attempt.Overall_Score__c);
        System.assert(attempt.Pass__c);
    }
    
}