practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Attempt_Score__c.object
<CustomObject>
    <fields>
        <fullName>Exam_Attempt__c</fullName>
        <label>Exam Attempt</label>
        <referenceTo>Exam_Attempt__c</referenceTo>
        <relationshipLabel>Attempt Scores</relationshipLabel>
        <relationshipName>Attempt_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weighted_Percent__c</fullName>
        <label>Weighted Percent</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <label>Attempt Score</label>
    <nameField>
        <displayFormat>Score-{00000}</displayFormat>
        <label>Attempt Score Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attempt Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Batch__c.object
<CustomObject>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Batch</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Batch_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Associate__c</fullName>
        <label>Associate</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Batch Assignments</relationshipLabel>
        <relationshipName>Batch_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Batch__c</fullName>
        <label>Batch</label>
        <referenceTo>Batch__c</referenceTo>
        <relationshipLabel>Associates</relationshipLabel>
        <relationshipName>Batch_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PD1_Certified__c</fullName>
        <formula>Associate__r.PD1_Certified__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PD1 Certified</label>
        <type>Checkbox</type>
    </fields>
    <label>Batch Assignment</label>
    <nameField>
        <displayFormat>{YY}{MM}-{0000}</displayFormat>
        <label>Batch Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Admin_Certified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Admin Certified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PD1_Certified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PD1 Certified</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Exam_Attempt__c.object
<CustomObject>
    <fields>
        <fullName>Associate__c</fullName>
        <label>Associate</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Exam Attempts</relationshipLabel>
        <relationshipName>Exam_Attempts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Attempt_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Attempt Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Days_Since_Start_Of_Batch__c</fullName>
        <label>Days Since Start Of Batch</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Exam_Type__c</fullName>
        <defaultValue>$CustomMetadata.Exam_Type__mdt.ADM_201.Label</defaultValue>
        <label>Exam Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Exam_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Overall_Score__c</fullName>
        <label>Overall Score</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Pass__c</fullName>
        <formula>(TEXT(Exam_Type__c) =  $CustomMetadata.Exam_Type__mdt.ADM_201.MasterLabel 
     &amp;&amp;  Overall_Score__c  &gt;=   $CustomMetadata.Exam_Type__mdt.ADM_201.Passing_Score__c)
||
(TEXT(Exam_Type__c) =  $CustomMetadata.Exam_Type__mdt.PD1.MasterLabel 
     &amp;&amp;  Overall_Score__c  &gt;=   $CustomMetadata.Exam_Type__mdt.PD1.Passing_Score__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pass</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Practice_Exam_Version__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Practice Exam Version</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Exam Attempt</label>
    <nameField>
        <displayFormat>Attempt-{0000}</displayFormat>
        <label>Exam Attempt ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Attempts</pluralLabel>
    <recordTypes>
        <fullName>Certification</fullName>
        <active>true</active>
        <label>Certification</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/force-app/main/default/globalValueSets/Exam_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ADM 201</fullName>
    </customValue>
    <customValue>
        <fullName>PD1</fullName>
    </customValue>
    <masterLabel>Exam Types</masterLabel>
</GlobalValueSet>

practice-exam-tracker-sfdx/pet-app/main/default/classes/ExamValidationAndUpdateHelper.cls
public class ExamValidationAndUpdateHelper {
    
    public static Map<Id, Date> getBatchStartDateByAssociate(Set<Id> associateIds){
        Map<Id, Date> associateIdStartDateMap = new Map<Id, Date>();
        
        for(Batch_Assignment__c ba : [SELECT Associate__c, Batch__r.Start_Date__c FROM Batch_Assignment__c
                                      WHERE Associate__c IN :associateIds]){
                                          associateIdStartDateMap.put(ba.Associate__c, ba.Batch__r.Start_Date__c);
                                      }
        return associateIdStartDateMap;
    }
    
    public static void updateExamAttemptDaysSinceStart(List<Exam_Attempt__c> attemptsList){
        Map<Id, Exam_Attempt__c> associateIdToExamAttemptMap = new Map<Id, Exam_Attempt__c>();
        for(Exam_Attempt__c ea : attemptsList){
            associateIdToExamAttemptMap.put(ea.Associate__c, ea);
        }
        Map<Id, Date> associateIdStartDateMap = getBatchStartDateByAssociate(associateIdToExamAttemptMap.keySet());
        //Map<Id, Exam_Attempt__c> examAttemptMap = new Map<Id, Exam_Attempt__c>();
        for(Id i : associateIdStartDateMap.keySet()){
            for(Exam_Attempt__c ea : attemptsList){
                if(ea.Associate__c == i){
                    ea.Days_Since_Start_Of_Batch__c = associateIdStartDateMap.get(i).daysBetween(ea.Attempt_Date__c);
                }
            }
        }
        //return examAttemptMap;
    }  

    public static void updateAssociateCertificationStatus(List<Exam_Attempt__c> attemptsList){
        Set<Id> associateIds = new Set<Id>();
        List<Contact> associatesToUpdate = new List<Contact>();
        for(Exam_Attempt__c ea : attemptsList){
            associateIds.add(ea.Associate__c);
        }
        List<AggregateResult> arList = [SELECT COUNT(Id), Exam_Type__c, Associate__c 
                                        FROM Exam_Attempt__c 
                                        WHERE Pass__c = true 
                                        AND Associate__c IN :associateIds 
                                        AND RecordTypeId = :Constants.EXAM_ATTEMPT_RECORD_TYPES.get('Certification').getRecordTypeId()
                                        GROUP BY Associate__c, Exam_Type__c];
        for(Id aId : associateIds){
            Contact a = new Contact(Id = aId, Admin_Certified__c = false, PD1_Certified__c = false);
            for(AggregateResult ar : arList){
                if(aId == (Id)ar.get('Associate__c') && (String)ar.get('Exam_Type__c') == 'ADM 201' ){
                  a.Admin_Certified__c = true;
                } else if (aId == (Id)ar.get('Associate__c') && (String)ar.get('Exam_Type__c') ==  'PD1'){
                    a.PD1_Certified__c = true;
                }
            }
            associatesToUpdate.add(a);
        }
        try {
            update associatesToUpdate;
        } catch (Exception e){
            System.debug('Something went wrong while trying to update the certification status of an Associate record.');
        }
    }
    
    public static void updateExamAttemptOverallScore(Set<ID> attemptIds){
        List<Exam_Attempt__c> attemptsToUpdate = new List<Exam_Attempt__c>();
        for(AggregateResult ar : [SELECT SUM(Weighted_Percent__c), Exam_Attempt__c FROM Attempt_Score__c
                                  WHERE Exam_Attempt__c IN :attemptIds
                                  GROUP BY Exam_Attempt__c]){
                                      System.debug('Overall Score: ' + (Decimal)ar.get('expr0'));
                                      attemptsToUpdate.add(new Exam_Attempt__c(Id = (Id)ar.get('Exam_Attempt__c'),
                                                                               Overall_Score__c = (Decimal)ar.get('expr0')));   
                                  }
        try {
            update attemptsToUpdate;
        } catch (Exception e){
            System.debug('Something went wrong while trying to update the overall score of exam attempts.');
        }
    }
    
    public static void updatePracticeExamVersionForCertAttempts(List<Exam_Attempt__c> attempts){
        for(Exam_Attempt__c ea : attempts){
            if(ea.RecordTypeId == Constants.EXAM_ATTEMPT_RECORD_TYPES.get('Certification').getRecordTypeId()){
                ea.Practice_Exam_Version__c = 0;
            }
        }
    }
    
}