practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Attempt_Score__c.object
<CustomObject>
    <fields>
        <fullName>Exam_Attempt__c</fullName>
        <label>Exam Attempt</label>
        <referenceTo>Exam_Attempt__c</referenceTo>
        <relationshipLabel>Attempt Scores</relationshipLabel>
        <relationshipName>Attempt_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Exam_Category__c</fullName>
        <label>Exam Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Exam_Categories</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Percent__c</fullName>
        <label>Percent</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Attempt Score</label>
    <nameField>
        <displayFormat>Score-{00000}</displayFormat>
        <label>Attempt Score Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attempt Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Exam_Attempt__c.object
<CustomObject>
    <fields>
        <fullName>Exam_Type__c</fullName>
        <defaultValue>$CustomMetadata.Exam_Type__mdt.ADM_201.Label</defaultValue>
        <label>Exam Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Exam_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Exam Attempt</label>
    <nameField>
        <displayFormat>Attempt-{0000}</displayFormat>
        <label>Exam Attempt ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/force-app/main/default/globalValueSets/Exam_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Organizational Setup</fullName>
    </customValue>
    <customValue>
        <fullName>User Setup</fullName>
    </customValue>
    <customValue>
        <fullName>Security and Access</fullName>
    </customValue>
    <customValue>
        <fullName>Standard and Custom Objects</fullName>
    </customValue>
    <customValue>
        <fullName>Sales and Marketing Applications</fullName>
    </customValue>
    <customValue>
        <fullName>Service and Support Applications</fullName>
    </customValue>
    <customValue>
        <fullName>Activity Management and Collaboration</fullName>
    </customValue>
    <customValue>
        <fullName>Data Management</fullName>
    </customValue>
    <customValue>
        <fullName>Analytics-Reports and Dashboards</fullName>
    </customValue>
    <customValue>
        <fullName>Workflow / Process Automation</fullName>
    </customValue>
    <customValue>
        <fullName>Desktop and Mobile Administration</fullName>
    </customValue>
    <customValue>
        <fullName>AppExchange</fullName>
    </customValue>
    <customValue>
        <fullName>Data Modeling and Management</fullName>
    </customValue>
    <customValue>
        <fullName>Debug and Deployment Tools</fullName>
    </customValue>
    <customValue>
        <fullName>Logic and Process Automation</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce Fundamentals</fullName>
    </customValue>
    <customValue>
        <fullName>Testing</fullName>
    </customValue>
    <customValue>
        <fullName>User Interface</fullName>
    </customValue>
    <masterLabel>Exam Categories</masterLabel>
</GlobalValueSet>

practice-exam-tracker-sfdx/force-app/main/default/globalValueSets/Exam_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ADM 201</fullName>
    </customValue>
    <customValue>
        <fullName>PD1</fullName>
    </customValue>
    <masterLabel>Exam Types</masterLabel>
</GlobalValueSet>

practice-exam-tracker-sfdx/force-app/main/default/classes/AttemptScoreFormController.cls
public class AttemptScoreFormController {

    
    @AuraEnabled
    public static String getExamTypeFromAttemptId(Id attemptId){
    	String examType = [SELECT Exam_Type__c FROM Exam_Attempt__c WHERE Id = :attemptId].Exam_Type__c;
        return examType;
    }
    
    @AuraEnabled
    public static List<Attempt_Score__c> getAttemptScoreTemplatesForExamType(String examType, Id attemptId){
        List<Attempt_Score__c> scores = new List<Attempt_Score__c>();
        for(String s : Constants.EXAM_TYPE_TO_CATEGORY_MAP.get(examType)){
            Attempt_Score__c score = new Attempt_Score__c(Exam_Attempt__c = attemptId, Exam_Category__c = s, Percent__c = null);
            scores.add(score);
        }
        return scores;
    }
    
    @AuraEnabled
    public static void insertAttemptScores(List<Attempt_Score__c> scoresToInsert){
        try{
            insert scoresToInsert;
        } catch (Exception e){
            System.debug('Something went wrong while trying to insert new attempt scores.');
        }
    }
    
}