practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Batch__c.object
<CustomObject>
    <label>Batch</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Batch_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Associate__c</fullName>
        <label>Associate</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Batch Assignments</relationshipLabel>
        <relationshipName>Batch_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Batch__c</fullName>
        <label>Batch</label>
        <referenceTo>Batch__c</referenceTo>
        <relationshipLabel>Associates</relationshipLabel>
        <relationshipName>Batch_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Batch Assignment</label>
    <nameField>
        <displayFormat>{YY}{MM}-{0000}</displayFormat>
        <label>Batch Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/sfdx project/classes/BatchAssignmentValidationHelper.cls
public class BatchAssignmentValidationHelper {

    public static void preventDuplicates(List<Batch_Assignment__c> assignments){
        List<AggregateResult> arList = [SELECT COUNT(Id), Batch__c, Associate__c FROM Batch_Assignment__c
                                       GROUP BY Batch__c, Associate__c];
        for(AggregateResult ar : arList){
            for(Batch_Assignment__c ba : assignments){
                if(((Id)ar.get('Batch__c') == ba.Batch__c) && ((Id)ar.get('Associate__c') == ba.Associate__c)){
                    if((Integer)ar.get('expr0') != null && (Integer)ar.get('expr0') != 0){
                        ba.addError('This associate is already assigned to this batch.');
                    }
                }
            }
        }
    }
    
}