practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Batch__c.object
<CustomObject>
    <fields>
        <fullName>Length__c</fullName>
        <description>Number of weeks that the training will run.</description>
        <label>Length</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Batch</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Batch_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Associate__c</fullName>
        <label>Associate</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Batch Assignments</relationshipLabel>
        <relationshipName>Batch_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Batch__c</fullName>
        <label>Batch</label>
        <referenceTo>Batch__c</referenceTo>
        <relationshipLabel>Associates</relationshipLabel>
        <relationshipName>Batch_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Batch Assignment</label>
    <nameField>
        <displayFormat>{YY}{MM}-{0000}</displayFormat>
        <label>Batch Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {

    public static List<Contact> createNAssociates(Integer n){
        List<Contact> associateList = new List<Contact>();
        for(Integer i = 0; i < n; i++){
            associateList.add(new Contact(LastName = 'Test ' + i));
        }
        return associateList;
    }
    
    public static List<Batch__c> createNBatches(Integer n){
        List<Batch__c> batchList = new List<Batch__c>();
        for(Integer i = 0; i < n; i++){
            batchList.add(new Batch__c(Name = 'Test' + i + '-Salesforce', Start_Date__c = Date.newInstance(2019, Math.mod(i, 12)+1, Math.mod(i, 29)+1), Length__c = 10));
        }
        return batchList;
    }
    
    public static List<Batch__c> createNBatches(Integer n, Date startDate){
        List<Batch__c> batchList = new List<Batch__c>();
        for(Integer i = 0; i < n; i++){
            batchList.add(new Batch__c(Name = 'Test' + i + '-Salesforce', Start_Date__c = startDate, Length__c = 10));
        }
        return batchList;
    }
    
    public static List<Batch_Assignment__c> createBatchAssignments(List<Contact> associates, Batch__c batch){
        List<Batch_Assignment__c> assignmentsList = new List<Batch_Assignment__c>();
        for(Contact c : associates){
            assignmentsList.add(new Batch_Assignment__c(Associate__c = c.Id, Batch__c = batch.Id));
        }
        return assignmentsList;
    }
    
}