practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Batch__c.object
<CustomObject>
    <fields>
        <fullName>Number_ADM_Certified__c</fullName>
        <label>Number ADM Certified</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_PD1_Certified__c</fullName>
        <label>Number PD1 Certified</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Batch</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Batch_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>ADM_Certified__c</fullName>
        <formula>Associate__r.Admin_Certified__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ADM Certified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Batch__c</fullName>
        <label>Batch</label>
        <referenceTo>Batch__c</referenceTo>
        <relationshipLabel>Associates</relationshipLabel>
        <relationshipName>Batch_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PD1_Certified__c</fullName>
        <formula>Associate__r.PD1_Certified__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PD1 Certified</label>
        <type>Checkbox</type>
    </fields>
    <label>Batch Assignment</label>
    <nameField>
        <displayFormat>{YY}{MM}-{0000}</displayFormat>
        <label>Batch Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/classes/CertificationCountHelper.cls
public class CertificationCountHelper {

    public static void updateBatchCertificationCount(List<Batch__c> batches){
        Map<Id, Batch__c> batchMap = new Map<Id, Batch__c>(batches);
        for(AggregateResult ar : [SELECT COUNT(Id) groupCount, Batch__c, ADM_Certified__c, PD1_Certified__c FROM Batch_Assignment__c
                                  WHERE Batch__c IN :batchMap.keySet() AND (ADM_Certified__c = true OR PD1_Certified__c = true)
                                  GROUP BY Batch__c, ADM_Certified__c, PD1_Certified__c]){
                                      Id batchId = (ID)ar.get('Batch__c');
                                      if((Boolean)ar.get('ADM_Certified__c')){
                                          Integer admCount = (Integer)ar.get('groupCount');
                                          Batch__c batch = batchMap.get(batchId);
                                          batch.Number_ADM_Certified__c = admCount;
                                          batchMap.put(batchId, batch);
                                      } else if ((Boolean)ar.get('PD1_Certified__c')){
                                          Integer pd1Count = (Integer)ar.get('groupCount');
                                          Batch__c batch = batchMap.get(batchId);
                                          batch.Number_PD1_Certified__c = pd1Count;
                                          batchMap.put(batchId, batch);
                                      }
                                  }
        try {
            update batchMap.values();
        } catch (Exception e){
            System.debug(LoggingLevel.ERROR, 'Something went wrong when updating certification counts.');
            System.debug(LoggingLevel.ERROR, e.getMessage());
        }
    }
    
}