practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Batch__c.object
<CustomObject>
    <fields>
        <fullName>Length__c</fullName>
        <description>Number of weeks that the training will run.</description>
        <label>Length</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_ADM_Certified__c</fullName>
        <label>Number ADM Certified</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_PD1_Certified__c</fullName>
        <label>Number PD1 Certified</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Batch</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Batch_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Associate__c</fullName>
        <label>Associate</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Batch Assignments</relationshipLabel>
        <relationshipName>Batch_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Batch__c</fullName>
        <label>Batch</label>
        <referenceTo>Batch__c</referenceTo>
        <relationshipLabel>Associates</relationshipLabel>
        <relationshipName>Batch_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PD1_Certified__c</fullName>
        <formula>Associate__r.PD1_Certified__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PD1 Certified</label>
        <type>Checkbox</type>
    </fields>
    <label>Batch Assignment</label>
    <nameField>
        <displayFormat>{YY}{MM}-{0000}</displayFormat>
        <label>Batch Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/sfdx project/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Admin_Certified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Admin Certified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PD1_Certified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PD1 Certified</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

practice-exam-tracker-sfdx/PackageFormat/classes/CertificationCountHelperTest.cls
@isTest
public class CertificationCountHelperTest {

    @testSetup
    public static void setup(){
        Batch__c batch = new Batch__c(Name = '190311-Salesforce', Start_Date__c = Date.newInstance(2019, 03, 11), Length__c = 10);
        insert batch;
        
        List<Contact> contacts = new List<Contact>();
        for(Integer i = 0; i < 5; i++){
            Contact con = new Contact(LastName = 'Test ' + i);
            contacts.add(con);
        }
        insert contacts;
        
        List<Batch_Assignment__c> assignments = new List<Batch_Assignment__c>();
        for(Contact con : contacts){
            assignments.add(new Batch_Assignment__c(Associate__c = con.Id, Batch__c = batch.Id));
        }
        insert assignments;
    }
    
    @isTest
    public static void singlePositiveUpdateBatchCertificationCountTest(){
        List<Contact> associates = [SELECT Id, Admin_Certified__c, PD1_Certified__c FROM Contact];
        for(Contact c : associates){
            c.Admin_Certified__c = true;
        }
        update associates;
        
        Batch__c batch = [SELECT Id, Number_ADM_Certified__c, Number_PD1_Certified__c FROM Batch__c LIMIT 1];
        System.assertEquals(5, batch.Number_ADM_Certified__c);
        System.assertEquals(0, batch.Number_PD1_Certified__c);
    }
    
}