practice-exam-tracker-sfdx/ooo-app/main/default/objects/Question_Subtopic__c/Question_Subtopic__c.object-meta.xml
<CustomObject>
    <label>Question Subtopic</label>
    <nameField>
        <label>Question Subtopic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Subtopics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/ooo-app/main/default/objects/Question_Topic__c/Question_Topic__c.object-meta.xml
<CustomObject>
    <label>Question Topic</label>
    <nameField>
        <label>Question Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/ooo-app/main/default/objects/Topic_Covered__c/Topic_Covered__c.object-meta.xml
<CustomObject>
    <label>Topic Covered</label>
    <nameField>
        <displayFormat>CT #{0000}</displayFormat>
        <label>Covered Topic Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Topics Covered</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/ooo-app/main/default/objects/Topic_Covered__c/fields/Subtopic_Covered__c.field-meta.xml
<CustomField>
    <fullName>Subtopic_Covered__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subtopic Covered</label>
    <referenceTo>Question_Subtopic__c</referenceTo>
    <relationshipLabel>Weeks Covered</relationshipLabel>
    <relationshipName>Weeks_Covered</relationshipName>
    <type>Lookup</type>
</CustomField>

practice-exam-tracker-sfdx/ooo-app/main/default/objects/Topic_Covered__c/fields/Topic_Covered__c.field-meta.xml
<CustomField>
    <fullName>Topic_Covered__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Topic Covered</label>
    <referenceTo>Question_Topic__c</referenceTo>
    <relationshipLabel>Weeks Covered</relationshipLabel>
    <relationshipName>Weeks_Covered</relationshipName>
    <type>Lookup</type>
</CustomField>

practice-exam-tracker-sfdx/ooo-app/main/default/objects/Topic_Covered__c/fields/Week__c.field-meta.xml
<CustomField>
    <fullName>Week__c</fullName>
    <label>Week</label>
    <referenceTo>Week__c</referenceTo>
    <relationshipLabel>Topics Covered</relationshipLabel>
    <relationshipName>Topics_Covered</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

practice-exam-tracker-sfdx/ooo-app/main/default/objects/Week__c/Week__c.object-meta.xml
<CustomObject>
    <label>Week</label>
    <nameField>
        <label>Week Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weeks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

practice-exam-tracker-sfdx/ooo-app/main/default/classes/NewWeekFormController.cls
public class NewWeekFormController {

    @AuraEnabled
    public static Map<Id, String> getAvailableTopics(){
        Map<Id, String> availTopics = new Map<Id, String>();
        for(Question_Topic__c qt : [SELECT Id, Name FROM Question_Topic__c WHERE Active__c = true]){
            availTopics.put(qt.Id, qt.Name);
        }
        return availTopics;
    }
    
    @AuraEnabled
    public static Map<Id, String> getAvailableSubtopics(){
        Map<Id, String> availSubtopics = new Map<Id, String>();
        for(Question_Subtopic__c qs : [SELECT Id, Name FROM Question_Subtopic__c WHERE Active__c = true]){
            availSubtopics.put(qs.Id, qs.Name);
        }
        return availSubtopics;
    }
    
    @AuraEnabled
    public static void createWeekAndTopicsCoveredForBatch(Week__c newWeek, List<Id> topicsCovered, List<Id> subtopicsCovered){
        try {
            insert newWeek;
            createTopicsCoveredForWeek(newWeek.Id, topicsCovered, subtopicsCovered);
        } catch (Exception e){
            throw new AuraHandledException('An exception was thrown while trying to insert a new week record.');
        }
    }
    
    @AuraEnabled
    public static void createTopicsCoveredForWeek(Id weekId, List<Id> topicsCovered, List<Id> subtopicsCovered){
        List<Topic_Covered__c> toInsert = new List<Topic_Covered__c>();
        if(topicsCovered != null && topicsCovered.size() > 0){
            for(Id i : topicsCovered){
                toInsert.add(new Topic_Covered__c(Week__c = weekId, Topic_Covered__c = i));
            }
        }
        if(subtopicsCovered != null && subtopicsCovered.size() > 0){
            for(Id i : subtopicsCovered){
                toInsert.add(new Topic_Covered__c(Week__c = weekId, Subtopic_Covered__c = i));
            }
        }
        try {
            if(toInsert.size() != 0){
                insert toInsert;
                System.debug(toInsert);
                System.debug('Success!');
            }
        } catch(Exception e){
            throw new AuraHandledException('An exception was thrown while trying to insert a topic covered records.');
        }
        
    }
    
}